import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiRedux,
  SiReactquery,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMongoose,
  SiJsonwebtokens,
  SiSocketdotio,
  SiGit,
  SiGithub,
  SiFigma,
  SiPostman,
  SiVitest,
  SiJest,
  SiTestinglibrary,
  SiVercel,
  SiNetlify,
  SiRender,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';
import { BsOpenai } from 'react-icons/bs';

export const TECH_ICONS = {
  'JavaScript (ES6+)': SiJavascript,
  'TypeScript': SiTypescript,
  'React.js': SiReact,
  'Redux Toolkit': SiRedux,
  'Redux': SiRedux,
  'TanStack Query': SiReactquery,
  'Tailwind CSS': SiTailwindcss,
  'HTML5': SiHtml5,
  'CSS3': SiCss,
  'Node.js': SiNodedotjs,
  'Express.js': SiExpress,
  'MongoDB': SiMongodb,
  'Mongoose': SiMongoose,
  'JWT Auth': SiJsonwebtokens,
  'Socket.io': SiSocketdotio,
  'Git & GitHub': SiGithub,
  'Git': SiGit,
  'GitHub': SiGithub,
  'Figma': SiFigma,
  'Postman': SiPostman,
  'Vitest': SiVitest,
  'Jest': SiJest,
  'React Testing Library': SiTestinglibrary,
  'Vercel': SiVercel,
  'Netlify': SiNetlify,
  'Render': SiRender,
  'VS Code': VscVscode,
  'OpenAI API': BsOpenai,
};
